services:
  checker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: playwright-checker
    env_file:
      - ../.env
    volumes:
      - ./playwright-report:/app/playwright-report
    working_dir: /app
    command: yarn start
