services:
  checker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: disney-restaurant-checker
    # コンテキストルートはプロジェクトルートだが.envファイルはcompose.yamlからの位置で指定する
    env_file:
      - ../.env
    working_dir: /app
    volumes: []
    command: sh -c "xvfb-run --auto-servernum --server-args='-screen 0 1280x800x24' yarn tsx src/runner.ts"
